---
title: "Beta not related"
author: "Jincheng Wang"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE)
# Loading library here
library(tidyverse)
library(extrafont)
# library(biomformat)
library(qiime2R)
library(phyloseq)
library(patchwork)

sessionInfo()
np = switch(Sys.info()[['sysname']], Windows = 1, Darwin = 4)
```

```{r, eval=FALSE}
# import metadata
mf <- read.delim("../data/processed-data/Metadata_Baby_Seeding_all_samples_final.txt", header = T, sep = "\t", na.strings = c("", "NA"), stringsAsFactors = F)

mf_t <- mf %>% filter(date_sampling_category_days_continuous<=90, date_sampling_category_days_continuous>=30, mom_baby=="Baby", country=="USA", project_name!="ECAM", birth_mode_ms != "CSseed", body_site_type=="Fecal")
write.table(mf_t, file = "tmp_beta_not_related.txt", quote = F, sep = "\t", row.names = F)
```
### Filter feature table in qiime
```{qiime}
qiime feature-table filter-samples --i-table ../data/processed-data/table.qza --m-metadata-file tmp_beta_not_related.txt --o-filtered-table table_beta_not_related.qza
```
### Import feature table with only control samples
```{r, eval=FALSE}
# filtered feature table contain only control samples
ft_qza <- read_qza("table_beta_not_related.qza")

## feature table in dataframe
ft <- ft_qza$data %>% as.data.frame() %>% rownames_to_column(var = "otu_id") %>% filter(rowSums(.[,-1])!=0)

# actual sequencing count
seqcount <- ft[, -1] %>% colSums()
## Metadata only with samples that have sequences

mf_ft <- mf_t %>% filter(sample_name %in% colnames(ft))
```

3. Merge all things into a phyloseq object (no need to run)
```{r, eval=FALSE}
otu <- otu_table(ft %>% column_to_rownames(var = "otu_id"), taxa_are_rows = T)

tree <- read_qza("../data/processed-data/tree.qza")
tree <- ape::keep.tip(tree$data, rownames(otu_table(otu)))

# this object have the otu table, metadata and the phylogenetic tree
phylo <- merge_phyloseq(otu, sample_data(mf_ft %>% column_to_rownames(var = "sample_name")), tree)
phylo <- filter_taxa(phylo, function(x) {sum(x)>0}, prune = T)
```
```{r}
phylo_6k <- rarefy_even_depth(phylo, sample.size = 6000, rngseed = 20, replace = F, trimOTUs = T)
mf_6k <- sample_data(phylo_6k) %>% as.matrix() %>% as.data.frame() %>% rownames_to_column("sample_name")
```


### Beta diversity comparison
```{r}

beta_dist <- lapply(c("bray", "unifrac", "wunifrac"), function(x){distance(phylo_6k, method = x)})
names(beta_dist) = c("bray", "unifrac", "wunifrac")

beta_ord <- lapply(beta_dist, function(x){ordinate(phylo_6k, "PCoA", distance = x)})


p_list <- lapply(seq_along(beta_ord), function(x){plot_ordination(phylo_6k, beta_ord[[x]], color = "birth_mode_ms", shape = "date_sampling_category_days", title = names(beta_ord)[[x]])})
names(p_list) <- c("bray", "unifrac", "wunifrac")

wrap_plots(p_list) + plot_layout(guides = "collect") & theme_bw(base_size = 10) + theme(aspect.ratio = 1)
ggsave("beta_not_related.pdf", width = 12, useDingbats = F)

ss_cs_30 <- mf_6k %>% filter(date_sampling_category_days_continuous==30, birth_mode_ms=="CS")
ss_dist <- lapply(beta_dist, function(x){(x %>% as.matrix())[, ss_cs_30$sample_name] %>% rowSums()})
ss_dist_tbl <- lapply(seq_along(ss_dist), function(x){data.frame(sample_name = names(ss_dist[[x]]), distance = ss_dist[[x]]/4, method = names(ss_dist)[[x]]) %>% filter(!sample_name %in% ss_cs_30$sample_name)}) %>% do.call("rbind", .) %>% merge(., mf_6k, by = 1, all.x = T) %>% filter(birth_mode_ms=="Vag", exclusive_breastfeed=="Yes")

ggplot(ss_dist_tbl, aes(x = method, y = distance)) +
    geom_point(aes(color = date_sampling_category_days))

ss_dist_tbl2 <- ss_dist_tbl %>% filter(date_sampling_category_days_continuous==30) %>% group_by(method) %>% arrange(desc(distance)) %>% filter(seq(n())<=15)
ss_dist_tbl2 %>% pivot_wider(id_cols = c(sample_name, baby_sex), names_from = method, values_from = distance) %>% View

```